In [1]:
import numpy as np

In [2]:
# Create a table of zeros with shape (3, 4)
ar = np.zeros((5, 5))
print("ar:\n", ar)

# Create a table of ones with shape (2, 5)
arr = np.ones((5, 5))
print("arr:\n", arr)


ar:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
arr:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [3]:
#Creating a table in numpy using the zeros and ones into A Modified Table
arrr= np.zeros((5,5), dtype= int)
arrr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [4]:
arrr[0,:]=1
arrr[1,0:5:4]=1
arrr[2,0:5:2]=1
arrr[3,0:5:4]=1
arrr[4,:]=1

In [5]:
arrr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 1, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])